### ISSUE TITLE
Cross platform compatibility

### ISSUE THREAD

**Issue by philidem** [austinkelleher/porti#3]
The method spawning the Unix `lsof` process is not compatible with some operating systems.

How about you use raw `Socket` API to see if you can listen on random ports until you find one that is free?

**Comment by austinkelleher** [comment]
Thanks! `getRandomPort` now uses sockets, so it works on all platforms. https://github.com/austinkelleher/porti/commit/f8b52204bab6d35ccf66ab9591543a8f9ff46f5d

**Comment by philidem** [comment]
Nice!
